### ISSUE TITLE
Feature request: Custom email template

### ISSUE THREAD

**Issue by joshuabaker** [jalendport/craft-updatechecker#21]
We’d love to be able to adjust the email template. Do you have any thoughts on that, @lukeyouell?

**Comment by jalendport** [comment]
I've got some far-fetched ideas for the future of Update Checker, but in the meantime I might be able to add this as a feature 👍

**Comment by joshuabaker** [comment]
@jalendport Keen to clear my issues dashboard. Please can you review #24. If you’re happy it’s working, merge it. If you’re not, please close this issue regardless. 🙏🏻
